### ISSUE TITLE
trigger.py shows NaN and produces empty JLS files

### ISSUE THREAD

**Issue by andrew-ongh** [jetperch/pyjoulescope_examples#1]
Hello, 
I have a Joulescope and love it when using with the desktop application. 

I am trying to integrate it into my automated testing system but am stumbling with using "trigger.py". In theory, this script does everything I need without modification. In practice, it crashes. 

I was able to run "accumulators.py" with the following output: 
```
pyjoulescope_examples % python3 bin/accumulators.py                                                       
Accumulation in progress.
Updates displayed every 60 seconds.
Press CTRL-C to stop.

duration = 60 s, charge = -135 nC, energy = -70.7 nJ
duration = 120 s, charge = -264 nC, energy = -140 nJ
duration = 180 s, charge = -389 nC, energy = -207 nJ

```
it works. And it uses streaming, i.e. `device.start`. 
But trigger.py does not work. I connected OUT0 to IN1. 
I inserted a few print statements for clarification but it shows this: 

```
pyjoulescope_examples %     python3  bin/trigger.py --start rising --end falling --record --display_trigger 

Joulescope:002039
start 0
Voltage: 
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
Traceback (most recent call last):
  File "bin/trigger.py", line 518, in <module>
    run()
  File "bin/trigger.py", line 506, in run
    if capture(device.stream_buffer):
  File "bin/trigger.py", line 440, in __call__
    self._add(stream_buffer, start_id, trigger_id - 1)
  File "bin/trigger.py", line 378, in _add
    self._current.add(i)
  File "bin/trigger.py", line 183, in add
    self._mean += int(np.sum(v) * GAIN)
ValueError: cannot convert float NaN to integer
```

Joulescope JS110
Python 3.8.3
macOS 11.3.1

contextlib2==0.6.0.post1
cycler==0.10.0
docopt==0.6.2
joulescope==0.9.6
kiwisolver==1.3.1
libusb==1.0.23b7
matplotlib==3.4.2
numpy==1.20.3
Pillow==8.2.0
psutil==5.8.0
pymonocypher==3.1.0.0
pyparsing==2.4.7
python-dateutil==2.8.1
schema==0.7.4
six==1.16.0

**Comment by mliberty1** [comment]
Hi @andrew-ongh 

The math inside trigger.py was not handling NaN (missing samples) at all.  I was able to duplicate your behavior on a 13" macBook 2018 running macOS 11.3.1 and python 3.9.  It appears that the Mac drops samples when first starting the stream.  

I modified the trigger.py to handle and report the sample drops.  This does not prevent sample drops, but it does allow the trigger.py example to run on my macBook.

Could you please try the latest code `git pull` or copy from [trigger.py](https://github.com/jetperch/pyjoulescope_examples/blob/master/bin/trigger.py).

**Comment by andrew-ongh** [comment]
Hi Matt, 

Thanks for editing the script!
The script does not crash anymore. I am able to run it. I ran this for 5 minutes but it produces an empty CSV file:  

```
%     python3 bin/trigger.py --start rising --end falling --csv myout.csv --display_trigger --display_stats --self_test

start 28601
Ignored 7558 missing samples
stop 36161
start_time(samples),start_time(iso),end_time(samples),end_time(iso),current_mean(A),current_min(A),current_max(A),voltage_mean(V),voltage_min(V),voltage_max(V),power_mean(W),power_min(W),power_max(W),charge(C),charge(Ah),energy(J),energy(Wh)
28601,2021-06-18T05:29:34.479228,36161,2021-06-18T05:29:34.479659,NAN,NAN,NAN,NAN,NAN,NAN,NAN,NAN,NAN,0,0,0,0
^C        
```

[myout.csv](https://github.com/jetperch/pyjoulescope_examples/files/6674817/myout.csv)

This produces an empty JLS file: 
```
pyjoulescope_examples %     python3  bin/trigger.py --start rising --end falling --record --display_trigger

start 0
Ignored 123 missing samples
stop 125
start 28601
Ignored 9448 missing samples
stop 38051
^C
```
[20210618_050726_0002.jls.zip](https://github.com/jetperch/pyjoulescope_examples/files/6674828/20210618_050726_0002.jls.zip)

**Comment by mliberty1** [comment]
Hi @andrew-ongh - It now looks like you have another issue.  With this command:

```
python3 bin/trigger.py --start rising --end falling --csv myout.csv --display_trigger --display_stats --self_test
```

you should be seeing statistics displayed every other second due to the "self_test" trigger.  I read back to your first post, and you said that you connected OUT0 to IN1.  By default, the trigger is on IN0, so you need to connect OUT0 to IN0.  You may still see missing samples at the very beginning, but everything should run fine very soon (less than 1 second) after starting the script.

Does this fix the issue for you?

**Comment by andrew-ongh** [comment]
Yes, that fixes the issue.

**Comment by mliberty1** [comment]
Since this seems resolved, I am closing the issue.  Thanks!
