### ISSUE TITLE
jls_plot.py for jls2 not outputing correct stats

### ISSUE THREAD

**Issue by bauerjj** [jetperch/pyjoulescope_examples#11]
Hello,

I'm trying to get the `stats` from a jlsv2 capture that is only ~70s in duration. However the output stats shows the mean/min/max all incorrect. 

Capture:
`capture.py --jls2 --frequency 20000 --duration 70 --signals current,voltage,power ~/output.jls`

Plot:
`python3 ~/output.jls --stats --out ~/test.png`

`python3.10.6`
`pyjoulescope_driver == 1.3.11`

![test2](https://github.com/jetperch/pyjoulescope_examples/assets/1715776/5330da3b-e3d0-4748-a3ff-4764a0d9efa6)

**Comment by mliberty1** [comment]
Hi @bauerjj and sorry to hear that this is not working for you.  Could you try using pyjoulescope_driver directly?  

    pip3 install -U pyjls pyjoulescope_driver
    python3 -m pyjoulescope_driver record --frequency 20000 --duration 70 --signals current,voltage,power ~/output.jls

Does this then work for you:

    python3 jls_plot.py ~/output.jls --stats --out test.png

If not, can you please provide the output for:

    python3 -m pyjoulescope_driver info

And:

    python3 -m pyjls info ~/output.jls --verbose

**Comment by bauerjj** [comment]
@mliberty1 that worked, thanks!
