### ISSUE TITLE
bin/capture_simple.py is not working with JS220

### ISSUE THREAD

**Issue by KenneyQu** [jetperch/pyjoulescope_examples#12]
When I just run capture_simple.py, an error is reported. Is it out of date?
![image](https://github.com/jetperch/pyjoulescope_examples/assets/46238080/ac7f6dbc-4495-4082-9cb9-75c251718914)
![image](https://github.com/jetperch/pyjoulescope_examples/assets/46238080/2803fe05-bff3-4e10-91d0-39b33726fbc5)

![image](https://github.com/jetperch/pyjoulescope_examples/assets/46238080/fc5fcd84-ce04-43d7-b60a-52a80b43cee1)

**Comment by mliberty1** [comment]
Hi @KenneyQu - I see you closed this issue.  What ended up being the issue?

Also, if you want to record to a file, I now recommend using:

    python -m pyjoulescope_driver record --help

For example:

    python -m pyjoulescope_driver record --frequency 10000 --duration 4.0 --signals current,voltage,power my_file_name.jls

This uses the new, faster joulescope_driver backend directly.
