### ISSUE TITLE
Errors when running downsample_logging.py

### ISSUE THREAD

**Issue by ssozonoff** [jetperch/pyjoulescope_examples#14]
Hi,

I followed the ReadMe and recording start but shortly after the follow errors start to occur repeatedly.
I am running a JS110
Any thoughts ?

Thanks

2023-09-15T13:48:26 ERROR    status returned 11
2023-09-15T13:48:28 WARNING  ctrl_in timed out
2023-09-15T13:48:28 ERROR    status returned 11
2023-09-15T13:48:31 WARNING  ctrl_in timed out
2023-09-15T13:48:31 ERROR    status returned 11
2023-09-15T13:48:34 ERROR    handle_rsp unsupported !ctrl_in
2023-09-15T13:48:35 WARNING  ctrl_in timed out
2023-09-15T13:48:35 ERROR    status returned 11
2023-09-15T13:48:35 ERROR    handle_rsp unsupported !ctrl_in
2023-09-15T13:48:36 WARNING  ctrl_in timed out
2023-09-15T13:48:36 ERROR    status returned 11
2023-09-15T13:48:36 ERROR    handle_rsp unsupported !ctrl_in
2023-09-15T13:48:38 WARNING  ctrl_in timed out
2023-09-15T13:48:38 ERROR    status returned 11
2023-09-15T13:48:39 WARNING  ctrl_in timed out

**Comment by mliberty1** [comment]
Those messages indicate that your JS110 is not correctly communicating with the host.  A few questions:

1. What host OS and computer are you using?
2. Is the JS110 connected directly to a USB port on the host computer, no hubs, docks or adapters?
3. Does this same setup work with the Joulescope UI?
4. What version of python are you running?  You can type `python -VV`.  (two V, not one W)

**Comment by ssozonoff** [comment]
Hi,

1. Its Mac M1 running OSX Venutra.
2. The JS110 goes via an Apple USB to USB-C converter but thats it.
3. Joulscope UI seems to work fine.
4. Python 3.11.3 (main, Jun  5 2023, 13:12:00) [Clang 14.0.3 (clang-1403.0.22.14.1)]

Thanks,
Serge

**Comment by mliberty1** [comment]
Ok, macOS does some annoying power management that may prevent this script (and all others) from working.

Do you care about standard deviation?  If not, you can also try using on-instrument 2 Hz statistics.  Add the `--source sensor` command line argument to `downsample_logging.py`.  

In the Joulescope UI, we use [appnope](https://pypi.org/project/appnope/) to prevent macOS from performing app nap.  You could modify downsample_logging to have this.  First, `pip install appnope`.  Then just insert this near the top of `downsample_logging.py`:

    import appnope
    appnope.nope()

Does this help?

**Comment by ssozonoff** [comment]
Hi,

Neither option resolves the issue.

Thanks,
Serge

**Comment by mliberty1** [comment]
Ok, so I am not sure what is happening yet.  Let's try a few other things:

1. Is your mac plugged into power?
2. Do both the sensor-side LED under "IN" and the host-side "Status" LED remain illuminated when this occurs?
3. Does this command work: `python -m pyjoulescope_driver statistics`

**Comment by ssozonoff** [comment]
1. Yes
2. Yes they remain ON
3. Yes the statistics command seems to work fine over time where as the other will eventually (usually after a minute or two) start spewing out the errors.

**Comment by mliberty1** [comment]
Ok.  I do not understand what is happening with `downsample_logging.py` on your machine.  I just tried this on a MacBook Pro 13-inch 2020 M1 running macOS 13.4.1 (c) with python 3.11.5.  It has been running over 5 minutes.  I will keep it running and let you know if I see anything.

1. Are you running homebrew?  You can update everything: `brew update && brew upgrade`
2. You can also ensure that the python packages are up to date: `pip install -U --upgrade-strategy eager joulescope`
3. Does running `python -m pyjoulescope_driver statistics` get you what you need?

**Comment by ssozonoff** [comment]
OK thanks, I changed the USB adapter but that did not help nor did the upgrades. I am still going to try a different USB cable.

3. I dont know, I have to read-up and see what it does.

Thanks

**Comment by mliberty1** [comment]
I saw that I had a macOS update.  I updated to macOS 13.5.2, but `downsample_logging.py` still works for me.

However, I noticed a few log messages that I think indicates that the JS110 is still streaming samples even with the `--source sensor` argument.  It should not be, which significantly reduces the data rate and chance for errors.  If you only need statistics data from a single JS110 source, then `python -m pyjoulescope_driver statistics` is a great choice.

**Comment by ssozonoff** [comment]
Thanks. I was just hoping for a simple way to gather some data over a longer period of time.

**Comment by ssozonoff** [comment]
Hi.

Did this ever get fixed ?

`However, I noticed a few log messages that I think indicates that the JS110 is still streaming samples even with the --source sensor argument`

I am still unable to use downsample_logging.py

Thanks,
Serge

**Comment by mliberty1** [comment]
Hi @ssozonoff  - We did no further investigation since we could not duplicate the issue and you seemed to be OK.

We will try to duplicate this again.  

To confirm. is this the command you are having trouble with?
```
python3 downsample_logging.py --source sensor
```

**Comment by ssozonoff** [comment]
Hi.That’s correct. I have run a large bunch of updates Python, etc…. but no change. I have tried another USB cable, USB port and even an adapter but still getting the error.

Thanks,Serge

**Comment by ssozonoff** [comment]
![Uploading Screenshot 2024-03-05 at 22.12.48.png…]()

**Comment by ssozonoff** [comment]
![Screenshot 2024-03-05 at 22 12 48](https://github.com/jetperch/pyjoulescope_examples/assets/610904/518893ad-55d4-449a-a218-458746c20def)

**Comment by mliberty1** [comment]
Hi @ssozonoff 

There are really two problems here:
1. Your MacBook does not support JS110 sample streaming.
2. The downsample_logging.py script causes JS110 sample streaming, even with `--source sensor`.  I confirmed the sample streaming using a TotalPhase Beagle USB 5000.

I suspect that MacBook power management is causing (1).  However, we have not proven this.  Looking at the conversation above, I see that `appnope` did not solve the problem.

If we could fix (2), then (1) becomes less of an issue for the moment.  I took a closer look at `downsample_logging.py`.  While it still works, it was also the first script we wrote after launching the JS110.  Since the focus of this script is reliability, it really should now directly use `pyjoulescope_driver` and avoid the additional complexity of the `joulescope` package.  I have made these changes.

Can you please try out the latest [downsample_logging.py](https://github.com/jetperch/pyjoulescope_examples/blob/main/bin/downsample_logging.py) script?

Does this updated script now work for you?

**Comment by ssozonoff** [comment]
Hi Matt,

I tested the modified downsample_logging.py script you provided and it works fine. Thanks for porting it to use pyjoulescope_driver. 

Kind regards,
Serge
