### ISSUE TITLE
joulescope 0.8 is not compatible with downsample_logging.py

### ISSUE THREAD

**Issue by jumpycalm** [jetperch/pyjoulescope_examples#3]
requirements.txt's joulescope>=0.8.0 needs to be changed to joulescope>=0.9.0. I tested with 0.8.14, it does not work. I'm on Python 3.6.8. The latest joulescope needs Numpy 2.0. But Numpy 2.0 is not compatible with Python 3.6. In order to use downsample_logging.py, I have to use joulescope==0.9.3.

**Comment by mliberty1** [comment]
Agreed that we need to update the joulescope dependency.  I recommend that you use the latest and greatest, [0.9.6](https://pypi.org/project/joulescope/).  

pyjoulescope dropped python 3.6 support recently.  Many projects, including numpy and other Joulescope dependencies, follow [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html).

Any reason you are still stuck with Python 3.6?  At this point, you really should be running Python 3.8 or 3.9.

**Comment by jumpycalm** [comment]
Thank you mliberty1,

Unfortunately, I use the Joulescope at work. It is our company's policy to only use Python 3.6. I tested it on my personal computer which runs Python 3.9 and it works fine. joulescope 0.9.6 requires Numpy 2.0 and above.

**Comment by mliberty1** [comment]
Unfortunately, your company's policy to use 3.6 is in conflict with the guidance of the scientific python community.  I do recommend that you forward [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) to your company policymakers.  Python 3.6 support was dropped on Jun 23, 2020 (a year ago).  Python 3.7 support will be dropped on Dec 26, 2021, six months from now.  The pyjoulescope project is aligned with NEP 29.

You are welcome to continue using older pyjoulescope versions.  0.9.3 ([changelog](https://github.com/jetperch/pyjoulescope/blob/master/CHANGELOG.md)) was the last to support python 3.6.  I really would prefer that you run the latest and greatest (currently 0.9.6).  In addition to picking up a couple of significant fixes, it will allow us to provide support as needed.

I updated requirements.txt, and I am closing this issue.
