### ISSUE TITLE
Plot generated by read_by_callback.py is unusable. Is there another way to automate plot creation?

### ISSUE THREAD

**Issue by andrew-ongh** [jetperch/pyjoulescope_examples#4]
I generated a plot from read_by_callback.py for a duration of 1s and it is not readable 

![Screen Shot 2021-07-14 at 21 32 17 ](https://user-images.githubusercontent.com/82856733/125842216-3642147b-09fa-4cd5-a234-75a748e32309.png)

My goal is after using `trigger.py` to collect data, generate a plot for a 90s or longer capture and output an image like the main Joulescope GUI. 
![Screen Shot 2021-07-15 at 11 58 36 ](https://user-images.githubusercontent.com/82856733/125842675-320bedff-8e13-42c8-bee8-98330760a1c3.png)

I think the easiest way is to have `trigger.py` capture to a JLS file and then open the JLS file in the Joulescope application. Is there a way to automate that?

**Comment by mliberty1** [comment]
That read_by_callback.py figure generated by Matplotlib simply displays the waveform, no nice min/mean/max lines per pixel.

If you just want to display the captured JLS file with the Joulescope UI, you can launch the Joulescope UI with the JLS path as the sole argument.  It looks like you are on Mac, so something like:

    /Applications/joulescope.app/Contents/MacOS/joulescope_launcher /path/to/your/20210715_191227.jls

The Joulescope UI does not currently support automatically generating the PNG.  You will still need to export the PNG manually.

Does this get you what you want?

**Comment by andrew-ongh** [comment]
Opening Joulescope.exe with command-line arguments gets me very close to what I want. 


Now I just wish there was a way to maximize the window. I tried changing the Joulescope preferences but could not find a way to maximize the window. But I did set it to open on the "Oscilloscope" profile. 

This Ruby script is what I did to take the screenshot: 
```
      logger.debug "Taking Joulescope screenshot"
      # Open Joulescope window       
      pid = spawn("\"C:\\Program Files (x86)\\Joulescope\\joulescope.exe\" ./#{jls_file_name}")
      Process.detach(pid)
      sleep(5) # Wait for the window to open
      # Use screen capture program 
      stdout, stderr, status = Open3.capture3("screenCapture.bat #{image_file_name} Joulescope:")
      output = stdout + stderr
      logger.debug output
      
      jls_URL = aws_s3_upload_file(jls_file_name)
      img_URL = aws_s3_upload_file(image_file_name)

      `taskkill /f /im joulescope.exe`

```
screenCapture.bat: https://github.com/npocmaka/batch.scripts/blob/master/hybrids/.net/c/screenCapture.bat

I tried changing this batch script to maximize the window before screenshot. But I was not successful. Will try again later.

**Comment by mliberty1** [comment]
Instead of spawn, perhaps you can somehow call start?  This seems to start Joulescope maximized:

    cd "c:\Program Files (x86)\Joulescope"
    start /WAIT /MAX joulescope.exe

I also came across [this method](https://stackoverflow.com/questions/2790825/how-can-i-maximize-a-specific-window-with-python) that uses the "user32.dll" with ctypes in python.  Is something like this possible with ruby?

**Comment by mliberty1** [comment]
Yet another option is to modify the Joulescope UI to support a "--window_state maximized" argument that calls Qt's setWindowState(QtCore.Qt.WindowMaximized).  Turns out, this was really easy, and I already pushed the change to the [develop branch](https://github.com/jetperch/pyjoulescope_ui/commit/b684826c4adf9ab5ed112b081a8935f9a3b62710).

**Comment by mliberty1** [comment]
I believe that this issue is solved.  Please reopen and comment if the solution above does not work.
