### ISSUE TITLE
Suspect buffer handling in windowed_accum.py

### ISSUE THREAD

**Issue by jamesl-dm** [jetperch/pyjoulescope_examples#6]
The windowed accumulation queries the entire range of ids in the sample buffer here:

https://github.com/jetperch/pyjoulescope_examples/blob/f9384808b969cc26305201e8237e31079997118d/bin/windowed_accum.py#L86

But reads out only the unseen samples here:

https://github.com/jetperch/pyjoulescope_examples/blob/f9384808b969cc26305201e8237e31079997118d/bin/windowed_accum.py#L93

However the samples consumed from the readout are calculated as though the entire buffer was read out:
https://github.com/jetperch/pyjoulescope_examples/blob/f9384808b969cc26305201e8237e31079997118d/bin/windowed_accum.py#L111

I suggest clipping the range of ids on line 87 with:
```
if ((self.sample_id_last is not None) and (start_id < self.sample_id_last)):
            start_id = self.sample_id_last
```

**Comment by mliberty1** [comment]
Hi @jamesl-dm - Yes, you are definitely right that the starting sample id is not being managed correctly in the windowed_accum.py example.  The reuse of `sample_id` is confusing.  I cleaned up the code.  See 7b3e62115da34ed878d8e09173727e6d49badb78, ready for merging  in the [fix/6](https://github.com/jetperch/pyjoulescope_examples/compare/fix/6) branch.  Does this now look right to you, too?

**Comment by jamesl-dm** [comment]
I gave https://github.com/jetperch/pyjoulescope_examples/commit/7b3e62115da34ed878d8e09173727e6d49badb78 a test and it's working well. Joulescope scripting has been a dream to work with (esp. compared to the Otii and it's onerous subscription model) - thanks so much! Still my favourite bit of test equipment by a large margin.

**Comment by mliberty1** [comment]
Excellent!  I have merged the change back into the "master" branch (which I will rename to "main" soon).  I'm going to close this issue, but feel free to reopen it if you find anything else.

Thanks for identifying this issue.  Great to hear that scripting has been working well for you and that you are putting your Joulescope to good use!
