### ISSUE TITLE
pyjoulescope_examples/bin/trigger.py - CSV output column mismatch

### ISSUE THREAD

**Issue by anujfalcon** [jetperch/pyjoulescope_examples#9]
Given:
#start_time(samples),start_time(iso),end_time(samples),end_time(iso),current_mean(A),current_std(A),current_min(A),current_max(A),voltage_mean(V),voltage_std(V),voltage_min(V),voltage_max(V),power_mean(W),power_std(W),power_min(W),power_max(W),charge(C),charge(Ah),energy(J),energy(Wh)
14973824,2023-04-12T02:31:06.295320,35658196,2023-04-12T02:31:16.619216,-4.8016e-11,1.33845e-08,-7.17118e-08,7.45058e-08,20684370,-0.000181522,0.00104353,-0.00515497,0.00506212,20684370,0,0,0,0,20684370,-4.96578e-10,-1.37938e-13,0,0

That contains 20 column header with 23 column of values

Change suggested: 
Either shrink the number of samples inserted before the voltage, power and charge/energy columns into just one column (if they are equal) or add title/header to each of those additional columns.

**Comment by mliberty1** [comment]
Good catch, @anujfalcon !  Commit [06fb519](https://github.com/jetperch/pyjoulescope_examples/commit/06fb5197992e9feda026124f4bc135e467dd4904) added the missing headers.  This should be fixed now, but please reopen if you continue to see the issue.
